name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "23 4 * * 1"
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@b1722c1245f90604c2c348f9d1624af97ea8fc6e # v3.29.0
        with:
          sarif_file: scorecard.sarif
